### ISSUE TITLE
Fails when sampling multiple times

### ISSUE THREAD

**Issue by xuod** [brunzema/truncated-mvn-sampler#1]
Hi,

First of all, thanks for the cool package!

However I noted a problem, which is that when calling `sample()` multiple times, results become inconsistent. I didn't dive too much in the code yet, but I saw that the attributes holding the upper/lower limits and the covariance are updated in multiple places, which is probably causing the issue. I guess these should be fixed and temporary/updated ones should be computed once and stored in other attributes.

I will give it a go tomorrow!

**Comment by brunzema** [comment]
Hi,

glad you like it and thank you for using it!

Thank you for reporting the problem. It should be fixed with the last commit.
The permutation, Cholesky factor computation and optimization for optimal tilting parameters need to only be performed once for the truncated MVN. The results are now stored and reused for future sampling calls. That should also solve the problem of trying to reorder the covariance and bounds each time `sample(n)` is called and also should speed up future sampling calls.

To reset the factors you can now also call `reset()` on the truncated MVN object and the factors will be recomputed again when calling `sample(n)`.

Let me know, if that works for you. :)
